---
- name: hap-uk-cto-004-dev-read
  email: hap-uk-cto-004-devread@gmail12.com
  roles:
  - readonlyrole
- name: hap-uk-cto-004-dev-read2
  email: hap-uk-cto-004-devread2@gmail12.com
  roles:
  - admin
- name: hap-uk-cto-004-dev-admin1
  email: hap-uk-cto-004-devadmin1@gmail12.com
  roles:
  - superadmin
  - admin
