---
- name: abc-t0-test-023-dev-read
  email: abc-t0-test-023-devread@gmail12.com
  roles:
  - readonlyrole
- name: abc-t0-test-023-dev-read2
  email: abc-t0-test-023-devread2@gmail12.com
  roles:
  - admin
- name: abc-t0-test-023-dev-admin1
  email: abc-t0-test-023-devadmin1@gmail12.com
  roles:
  - superadmin2
  - admin
