    rbac:
    - role: super-admin
      permissions:
      - endpoint: "*"
        negative: false
        actions: "create,update,read,delete"
      - endpoint: "/groups"
        negative: false
        actions: "create,update,read,delete"
      - endpoint: "/groups/*"
        negative: false
        actions: "create,update,read,delete"
      - endpoint: "/groups/*/roles"
        negative: false
        actions: "create,update,read,delete"
