---
- group_name: group-for-readonly-demo1
  group_comment: readonly group
  roles:
  - workspace: demo1
    role: readonlyrole
- group_name: group-for-admins-demo1
  group_comment: Admin group
  roles:
  - workspace: demo1
    role: admin
