---
- group_name: tes9e892-2783-209e-aa92-54baetestagain
  group_comment: readonly group (new object ID)
  roles:
  - workspace: abc-t0-test-015-dev
    role: readonlyrole
- group_name: ei3d2292-2783-209e-aa92-89dkd2ltest015
  group_comment: Admin group (object ID)
  roles:
  - workspace: abc-t0-test-015-dev
    role: admin
