---
- group_name: group-for-readonly
  group_comment: readonly group
  roles:
  - workspace: demo1
    role: readonlyrole
  - workspace: demo2
    role: readonlyrole
- group_name: group-for-admins
  group_comment: Admin group
  roles:
  - workspace: demo1
    role: admin
  - workspace: demo2
    role: admin
  - workspace: demo3
    role: admin
