    config:
      portal: false
    rbac:
    - role: readonlyrole
      permissions:
      - endpoint: "*"
        negative: false
        actions: "read"
    - role: workspace-admin
      permissions:
      - endpoint: "*"
        negative: false
        actions: "create,update,read,delete"
    - role: admin
      permissions:
      - endpoint: "*"
        negative: false
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*/*"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*/*/*"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*/*/*/*"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*/*/*/*/*"
        negative: true 
        actions: "create,update,read,delete"
    - role: superadmin2
      permissions:
      - endpoint: "*"
        negative: false
        actions: "create,update,delete"
      - endpoint: "/admins/*"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/admin/*/roles"
        negative: true 
        actions: "create,update,read,delete"
      - endpoint: "/rbac/*"
        negative: true 
        actions: "create,update,read,delete"
    plugins:
    - name: "file-log"
      config:
        path: /dev/stdout
        reopen: false
    - name: "rate-limiting-advanced"
      config:
        limit:
          - 10
          - 20
        window_size:
          - 60
          - 120
        strategy: redis
        redis:
          host: redis.kong-hybrid-dp.svc.cluster.local
          port: 6479
        sync_rate: 1
    - name: "correlation-id"
      config:
        header_name: Kong-Request-ID
        generator: "uuid#counter"
        echo_downstream: false
  