permissions:
- endpoint: "*"
  negative: false
  actions: "create,update,read,delete"
- endpoint: "/rbac/*"
  negative: true 
  actions: "create,update,read,delete"
- endpoint: "/rbac/*/*"
  negative: true 
  actions: "create,update,read,delete"
- endpoint: "/rbac/*/*/*"
  negative: true 
  actions: "create,update,read,delete"
- endpoint: "/rbac/*/*/*/*"
  negative: true 
  actions: "create,update,read,delete"
- endpoint: "/rbac/*/*/*/*/*"
  negative: true 
  actions: "create,update,read,delete"