---
- name: abc-t0-test-004-dev-read
  email: abc-t0-test-004-devread@gmail12.com
  roles:
  - readonlyrole
- name: abc-t0-test-004-dev-read2
  email: abc-t0-test-004-devread2@gmail12.com
  roles:
  - admin
- name: abc-t0-test-004-dev-admin1
  email: abc-t0-test-004-devadmin1@gmail12.com
  roles:
  - superadmin
  - admin
