---
- group_name: we9e7892-2783-209e-aa92-54bae8d8bs990k
  group_comment: readonly group (object ID)
  roles:
  - workspace: abc-t0-test-010-dev
    role: readonlyrole
- group_name: ei3d2292-2783-209e-aa92-89dkd2lsme1alk
  group_comment: Admin group (object ID)
  roles:
  - workspace: abc-t0-test-010-dev
    role: admin
