---
- name: abc-t0-test-010-dev-read
  email: abc-t0-test-010-devread@gmail12.com
  roles:
  - readonlyrole
- name: abc-t0-test-010-dev-read2
  email: abc-t0-test-010-devread2@gmail12.com
  roles:
  - admin
- name: abc-t0-test-010-dev-admin1
  email: abc-t0-test-010-devadmin1@gmail12.com
  roles:
  - superadmin2
  - admin
