---
- name: hap-uk-cto-015-dev-read
  email: hap-uk-cto-015-devread@gmail12.com
  roles:
  - readonlyrole
- name: hap-uk-cto-015-dev-read2
  email: hap-uk-cto-015-devread2@gmail12.com
  roles:
  - admin
- name: hap-uk-cto-015-dev-admin1
  email: hap-uk-cto-015-devadmin1@gmail12.com
  roles:
  - superadmin2
  - admin
